source: docs

title: BYU ACT
description: Course materials for BYU Cybersecurity's Applications of Cybersecurity Training course
baseurl: "" # the subpath of your site, e.g. /blog
remote_theme: just-the-docs/just-the-docs

url: https://byu-itc-515r-act.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - spec/
  - tmp
  - .rspec
  - docs/assets/gradingTables
  - docs/assets/downloads/lecture12-systemd.md
  - docs/assets/downloads/lecture10-postgres-cheatsheet.md
  - docs/assets/downloads/lecture9-IPTABLES-CHEATSHEET.md
  - docs/ctf/midterm2.md
  - docs/misc
  # TODO: figure out where these go and remove the exclusion
  
enable_copy_code_button: true

nav_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

